force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <displayFormat>UN-{0000}</displayFormat>
        <label>Unit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Bathrooms__c.field-meta.xml
<CustomField>
    <fullName>Bathrooms__c</fullName>
    <label>Bathrooms</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Bedrooms__c.field-meta.xml
<CustomField>
    <fullName>Bedrooms__c</fullName>
    <label>Bedrooms</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Property_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property Name</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Rent_Amount__c.field-meta.xml
<CustomField>
    <fullName>Rent_Amount__c</fullName>
    <label>Rent Amount</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Name__c.field-meta.xml
<CustomField>
    <fullName>Unit_Name__c</fullName>
    <label>Unit Name</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UnitSearch.cls
public class UnitSearch {

    @InvocableMethod(label='Get Unit Names' description='Returns the list of Unit names corresponding to the specified Units' category='Unit__c')
    public static List<Unit__c> getUnits(List<String> unitIds) {
        
        List<Unit__c> unitRecords = new List<Unit__c>();
        if(unitIds.isEmpty())
        {
            unitRecords = [SELECT Unit_Name__c, Unit_Status__c, Rent_Amount__c, Property_Name__c, Bedrooms__c, Bathrooms__c FROM Unit__c];
        }
        else
        {
            unitRecords = [SELECT Unit_Name__c, Unit_Status__c, Rent_Amount__c, Property_Name__c, Bedrooms__c, Bathrooms__c FROM Unit__c WHERE Unit_Name__c in :unitIds];
        }
        return unitRecords;
    }
    
    /*@InvocableMethod(label='Get Units by Status' description='Returns the list of Unit names corresponding to the specified status' category='Unit__c')
    public static List<Unit__c> getUnitByStatus(List<String> unitStatus) {
        
        List<Unit__c> unitRecords = new List<Unit__c>();
        
        unitRecords = [SELECT Unit_Name__c, Unit_Status__c, Rent_Amount__c, Property_Name__c, Bedrooms__c, Bathrooms__c FROM Unit__c WHERE Unit_Status__c in :unitStatus];
        return unitRecords;
    }*/
}